[versions]
kotlin-core = "2.2.21"
kotlin-coroutines = "1.10.2"
ktlint = "1.7.1"

[libraries]
assertk = { module = "com.willowtreeapps.assertk:assertk-jvm", version = "0.28.1" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version = "3.2.3" }
junit-bom = { module = "org.junit:junit-bom", version = "5.14.1" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlin-coroutines" }
kotlin-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
ktlint-rule-engine-core = { module = "com.pinterest.ktlint:ktlint-rule-engine-core", version.ref = "ktlint" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.21" }
mockk-core = { module = "io.mockk:mockk", version = "1.14.6" }

# gradle plugins for build-logic
gradle-plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version = "1.23.8" }
gradle-plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "2.1.0" }
gradle-plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
gradle-plugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version = "14.0.1" }
gradle-plugin-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.34.0" }
